/**
 * DO NOT EDIT THIS FILE
 */

import React from "react";
import AlertComp from "./AlertComp";

export default function Product({ num }) {
  return (
    <p>
      Product {num} <AlertComp />
    </p>
  );
}
