/**
 * DO NOT EDIT THIS FILE
 */

import React from "react";
import AlertComp from "./AlertComp";

export default function User({ name }) {
  return (
    <div>
      <h2>User name : {name}</h2>
      <AlertComp />
    </div>
  );
}
