/**
 * DO NOT EDIT THIS FILE
 */

import React, { useState } from "react";
import ChallengeOne from "./pages/ChallengeOne";
import ChallengeTwo from "./pages/ChallengeTwo";
import ChallengeThree from "./pages/ChallengeThree";
import ChallengeFour from "./pages/ChallengeFour";
import ChallengeFive from "./pages/ChallengeFive";

const pages = [
  <ChallengeOne />,
  <ChallengeTwo />,
  <ChallengeThree />,
  <ChallengeFour />,
  <ChallengeFive />,
];

export default function App() {
  const [index, setIndex] = useState(0);
  return (
    <>
      {pages.map((_, i) => (
        <button
          data-testid={`btn-c${i + 1}`}
          key={i}
          onClick={() => setIndex(i)}
        >
          Challenge {i + 1}
        </button>
      ))}
      <br />
      <br />
      <div>{pages[index]}</div>
    </>
  );
}
